export * from "@app/types/section";
export * from "@app/types/project";
export * from "@app/types/about";
export * from "@app/types/contact";
export * from "@app/types/experience";
export * from "@app/types/service";
export * from "@app/types/testimonial";
export * from "@app/types/socialMedia";
export * from "@app/types/hero";
